"""add number

Revision ID: 24a1d78c451d
Revises: 5d5a27825ad2
Create Date: 2025-04-12 00:00:44.868481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24a1d78c451d'
down_revision: Union[str, None] = '5d5a27825ad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_signature', sa.Column('number_for_signature', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_signature', 'number_for_signature')
    # ### end Alembic commands ###
